$base = "D:\ClaudeCode\ngl-frac-spread"

Write-Host "Adding GitHub Pages deployment...`n" -ForegroundColor Cyan

$p = Join-Path $base ".github\workflows\deploy.yml"; $d = Split-Path $p
if (!(Test-Path $d)) { New-Item -ItemType Directory -Path $d -Force | Out-Null }
[System.IO.File]::WriteAllBytes($p, [System.Convert]::FromBase64String("bmFtZTogRGVwbG95IHRvIEdpdEh1YiBQYWdlcwoKb246CiAgcHVzaDoKICAgIGJyYW5jaGVzOiBbbWFpbl0KICB3b3JrZmxvd19kaXNwYXRjaDoKCnBlcm1pc3Npb25zOgogIGNvbnRlbnRzOiByZWFkCiAgcGFnZXM6IHdyaXRlCiAgaWQtdG9rZW46IHdyaXRlCgpjb25jdXJyZW5jeToKICBncm91cDogcGFnZXMKICBjYW5jZWwtaW4tcHJvZ3Jlc3M6IGZhbHNlCgpqb2JzOgogIGJ1aWxkOgogICAgcnVucy1vbjogdWJ1bnR1LWxhdGVzdAogICAgc3RlcHM6CiAgICAgIC0gbmFtZTogQ2hlY2tvdXQKICAgICAgICB1c2VzOiBhY3Rpb25zL2NoZWNrb3V0QHY0CgogICAgICAtIG5hbWU6IFNldHVwIE5vZGUKICAgICAgICB1c2VzOiBhY3Rpb25zL3NldHVwLW5vZGVAdjQKICAgICAgICB3aXRoOgogICAgICAgICAgbm9kZS12ZXJzaW9uOiAyMAogICAgICAgICAgY2FjaGU6IG5wbQoKICAgICAgLSBuYW1lOiBJbnN0YWxsIGRlcGVuZGVuY2llcwogICAgICAgIHJ1bjogbnBtIGluc3RhbGwKCiAgICAgIC0gbmFtZTogQnVpbGQKICAgICAgICBydW46IG5wbSBydW4gYnVpbGQKICAgICAgICBlbnY6CiAgICAgICAgICBWSVRFX0ZSRURfS0VZOiAke3sgc2VjcmV0cy5WSVRFX0ZSRURfS0VZIH19CgogICAgICAtIG5hbWU6IFVwbG9hZCBhcnRpZmFjdAogICAgICAgIHVzZXM6IGFjdGlvbnMvdXBsb2FkLXBhZ2VzLWFydGlmYWN0QHYzCiAgICAgICAgd2l0aDoKICAgICAgICAgIHBhdGg6IGRpc3QKCiAgZGVwbG95OgogICAgZW52aXJvbm1lbnQ6CiAgICAgIG5hbWU6IGdpdGh1Yi1wYWdlcwogICAgICB1cmw6ICR7eyBzdGVwcy5kZXBsb3ltZW50Lm91dHB1dHMucGFnZV91cmwgfX0KICAgIHJ1bnMtb246IHVidW50dS1sYXRlc3QKICAgIG5lZWRzOiBidWlsZAogICAgc3RlcHM6CiAgICAgIC0gbmFtZTogRGVwbG95IHRvIEdpdEh1YiBQYWdlcwogICAgICAgIGlkOiBkZXBsb3ltZW50CiAgICAgICAgdXNlczogYWN0aW9ucy9kZXBsb3ktcGFnZXNAdjQK"))
Write-Host "  created: .github\workflows\deploy.yml" -ForegroundColor Green

$p = Join-Path $base "vite.config.js"; $d = Split-Path $p
if (!(Test-Path $d)) { New-Item -ItemType Directory -Path $d -Force | Out-Null }
[System.IO.File]::WriteAllBytes($p, [System.Convert]::FromBase64String("aW1wb3J0IHsgZGVmaW5lQ29uZmlnIH0gZnJvbSAndml0ZScKaW1wb3J0IHJlYWN0IGZyb20gJ0B2aXRlanMvcGx1Z2luLXJlYWN0JwpleHBvcnQgZGVmYXVsdCBkZWZpbmVDb25maWcoewogIHBsdWdpbnM6IFtyZWFjdCgpXSwKICBiYXNlOiAnL25nbC1mcmFjLXNwcmVhZC8nLAogIGVzYnVpbGQ6IHsKICAgIGxvYWRlcjogJ2pzeCcsCiAgICBpbmNsdWRlOiAvc3JjXC8uKlwuKGpzfGpzeCkkLywKICB9LAogIG9wdGltaXplRGVwczogewogICAgZXNidWlsZE9wdGlvbnM6IHsgbG9hZGVyOiB7ICcuanMnOiAnanN4JywgJy5qc3gnOiAnanN4JyB9IH0KICB9Cn0pCg=="))
Write-Host "  created: vite.config.js" -ForegroundColor Green

Write-Host "\nDone! Now commit and push in GitHub Desktop." -ForegroundColor Green
